---
abstract: 'Auto handling of Devel::NYTProf in your Mojolicious app'
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  Test::Exception: 0.32
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-NYTProf
no_index:
  directory:
    - t
    - inc
requires:
  Devel::NYTProf: 5.06
  File::Spec::Functions: 3.30
  File::Temp: 0.22
  File::Which: 1.09
  Mojolicious: 4.24
  Time::HiRes: 1.9719
resources:
  bugtracker: https://github.com/leejo/mojolicious-plugin-nytprof/issues
  homepage: https://metacpan.org/module/Mojolicious::Plugin::NYTProf
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/mojolicious-plugin-nytprof
version: 0.01
